# permissions for end users to view foos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: blog-foo-viewer-role
rules:
- apiGroups:
  - blog.mydomain.com
  resources:
  - foos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - blog.mydomain.com
  resources:
  - foos/status
  verbs:
  - get
